# Generated by Django 2.0.13 on 2019-06-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='apellido_paterno',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='estado',
            field=models.CharField(choices=[('EN PROCESO', 'EN PROCESO'), ('DISPONIBLE', 'DISPONIBLE')], default='DISPONIBLE', max_length=80),
        ),
    ]
